"""create workspaces_imagery table and drop imageryList column from workspaces

Revision ID: 073a96d114ab
Revises: 279f8d753529
Create Date: 2025-09-09 07:58:35.746897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '073a96d114ab'
down_revision = '279f8d753529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces_imagery',
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('definition', sa.Unicode(), nullable=False),
    sa.Column('modifiedAt', sa.DateTime(), nullable=False),
    sa.Column('modifiedBy', sa.UUID(), nullable=False),
    sa.Column('modifiedByName', sa.Unicode(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_column('imageryList')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageryList', sa.VARCHAR(), autoincrement=False, nullable=True))

    op.drop_table('workspaces_imagery')
    # ### end Alembic commands ###
