"""Added imager list json string in workspaces table

Revision ID: 279f8d753529
Revises: fb96ef86e2f6
Create Date: 2025-09-03 06:02:36.696451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279f8d753529'
down_revision = 'fb96ef86e2f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageryList', sa.Unicode(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_column('imageryList')

    # ### end Alembic commands ###
