"""empty message

Revision ID: 83c21293dacc
Revises: 87b301fe4185
Create Date: 2024-04-12 02:31:55.775369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83c21293dacc'
down_revision = '87b301fe4185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tdeiMetadata', sa.Unicode(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_column('tdeiMetadata')

    # ### end Alembic commands ###
