"""Add workspaces model

Revision ID: 87b301fe4185
Revises: 42c45e74752b
Create Date: 2024-04-10 01:06:00.323404

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = '87b301fe4185'
down_revision = '42c45e74752b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(), nullable=True),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.Column('tdeiRecordId', sa.UUID(), nullable=True),
    sa.Column('tdeiProjectGroupId', sa.UUID(), nullable=True),
    sa.Column('tdeiServiceId', sa.UUID(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.UUID(), nullable=True),
    sa.Column('createdByName', sa.Unicode(), nullable=True),
    sa.Column('geometry', Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_geospatial_index('idx_workspaces_geometry', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_geospatial_index('idx_workspaces_geometry', postgresql_using='gist', column_name='geometry')

    op.drop_geospatial_table('workspaces')
    # ### end Alembic commands ###
