"""Add workspace long form quest type and URL fields

Revision ID: add6266277c7
Revises: c5121cbba124
Create Date: 2025-09-12 04:18:05.931799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "add6266277c7"
down_revision = "c5121cbba124"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workspaces_long_quests", schema=None) as batch_op:
        batch_op.add_column(sa.Column("type", sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column("url", sa.Unicode(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workspaces_long_quests", schema=None) as batch_op:
        batch_op.drop_column("type")
        batch_op.drop_column("url")

    # ### end Alembic commands ###
