"""Made quest definition nullable, imagery definition nullable

Revision ID: c5121cbba124
Revises: dd99815a393c
Create Date: 2025-09-16 09:49:13.381703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5121cbba124'
down_revision = 'dd99815a393c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces_imagery', schema=None) as batch_op:
        batch_op.alter_column('definition',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)

    with op.batch_alter_table('workspaces_long_quests', schema=None) as batch_op:
        batch_op.alter_column('definition',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces_long_quests', schema=None) as batch_op:
        batch_op.alter_column('definition',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('workspaces_imagery', schema=None) as batch_op:
        batch_op.alter_column('definition',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)

    # ### end Alembic commands ###
