"""Add Workspace model

Revision ID: cbc419d1740c
Revises: 6276c258149c
Create Date: 2024-09-25 03:44:52.993293

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cbc419d1740c'
down_revision = '6276c258149c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Unicode(), nullable=False),
    sa.Column('title', sa.Unicode(), nullable=False),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.Column('tdeiProjectGroupId', sa.UUID(), nullable=False),
    sa.Column('tdeiRecordId', sa.UUID(), nullable=True),
    sa.Column('tdeiServiceId', sa.UUID(), nullable=True),
    sa.Column('tdeiMetadata', sa.Unicode(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('createdBy', sa.UUID(), nullable=False),
    sa.Column('createdByName', sa.Unicode(), nullable=True),
    sa.Column('geometry', Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('externalAppAccess', sa.SmallInteger(), nullable=False),
    sa.Column('kartaViewToken', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_geospatial_index('idx_workspaces_geometry', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_geospatial_index('idx_workspaces_geometry', postgresql_using='gist', column_name='geometry')

    op.drop_geospatial_table('workspaces')
    # ### end Alembic commands ###
