"""Add on delete cascade to foreign keys

Revision ID: dd99815a393c
Revises: ae084e0b68b2
Create Date: 2025-09-11 12:57:04.904320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd99815a393c'
down_revision = 'ae084e0b68b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces_long_quests', schema=None) as batch_op:
        batch_op.drop_constraint('workspaces_long_quests_workspace_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(
            'workspaces_long_quests_workspace_id_fkey',
            'workspaces',
            ['workspace_id'],
            ['id'],
            ondelete='CASCADE'
        )

    with op.batch_alter_table('workspaces_imagery', schema=None) as batch_op:
        batch_op.drop_constraint('workspaces_imagery_workspace_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(
            'workspaces_imagery_workspace_id_fkey',
            'workspaces',
            ['workspace_id'],
            ['id'],
            ondelete='CASCADE'
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces_long_quests', schema=None) as batch_op:
        batch_op.drop_constraint('workspaces_long_quests_workspace_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(
            'workspaces_long_quests_workspace_id_fkey',
            'workspaces',
            ['workspace_id'],
            ['id']
        )

    with op.batch_alter_table('workspace_imagery', schema=None) as batch_op:
        batch_op.drop_constraint('workspace_imagery_workspace_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(
            'workspace_imagery_workspace_id_fkey',
            'workspaces',
            ['workspace_id'],
            ['id']
        )

    # ### end Alembic commands ###
