"""Add WorkspaceLongQuest model

Revision ID: fb96ef86e2f6
Revises: cbc419d1740c
Create Date: 2024-09-27 20:58:48.070862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb96ef86e2f6'
down_revision = 'cbc419d1740c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces_long_quests',
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('definition', sa.Unicode(), nullable=False),
    sa.Column('modifiedAt', sa.DateTime(), nullable=False),
    sa.Column('modifiedBy', sa.UUID(), nullable=False),
    sa.Column('modifiedByName', sa.Unicode(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspaces_long_quests')
    # ### end Alembic commands ###
